IF OBJECT_ID(N'[BM_EF_MIGRATIONS_HISTORY]') IS NULL
BEGIN
    CREATE TABLE [BM_EF_MIGRATIONS_HISTORY] (
        [MIGRATION_ID] nvarchar(150) NOT NULL,
        [PRODUCT_VERSION] nvarchar(32) NOT NULL,
        CONSTRAINT [PK_BM_EF_MIGRATIONS_HISTORY] PRIMARY KEY ([MIGRATION_ID])
    );
END;
GO

BEGIN TRANSACTION;
GO

IF NOT EXISTS(SELECT * FROM [BM_EF_MIGRATIONS_HISTORY] WHERE [MIGRATION_ID] = N'20250426215323_INITIAL')
BEGIN
    CREATE TABLE [BM_BOOKING] (
        [ID] int NOT NULL IDENTITY,
        [USER_NAME] nvarchar(max) NOT NULL,
        [ROOM_LINK_ID] int NOT NULL,
        [START_DATE] datetime2 NOT NULL,
        [END_DATE] datetime2 NOT NULL,
        [STATUS] nvarchar(max) NULL,
        [IS_DELETED] bit NOT NULL DEFAULT CAST(0 AS bit),
        [CREATED_DATE_TIME] datetime2 NOT NULL,
        [CREATED_BY] uniqueidentifier NULL,
        [CREATED_BY_USERNAME] nvarchar(max) NULL,
        [MODIFIED_DATE_TIME] datetime2 NOT NULL,
        [MODIFIED_BY] uniqueidentifier NULL,
        [MODIFIED_BY_USERNAME] nvarchar(max) NULL,
        CONSTRAINT [PK_BM_BOOKING] PRIMARY KEY ([ID])
    );
END;
GO

IF NOT EXISTS(SELECT * FROM [BM_EF_MIGRATIONS_HISTORY] WHERE [MIGRATION_ID] = N'20250426215323_INITIAL')
BEGIN
    INSERT INTO [BM_EF_MIGRATIONS_HISTORY] ([MIGRATION_ID], [PRODUCT_VERSION])
    VALUES (N'20250426215323_INITIAL', N'6.0.5');
END;
GO

COMMIT;
GO

